spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/aivms
    username: aivms_user
    password: aivms_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-AivmsLocal
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    de:
      syed:
        aivms: DEBUG